if GetLocale() == "frFR" then
  local _, core = ...;
  local CommDKP = core.CommDKP;
  
  core.BossList = {
    MC = {
      "Lucifron",
      "Magmadar",
      "Gehennas",
      "Garr",
      "Baron Geddon",
      "Shazzrah",
      "Messager de Sulfuron",
      "Golemagg l'Incinérateur",
      "Chambellan Executus",
      "Ragnaros",
    },
    BWL = {
      "Tranchetripe l'Indompté",
      "Vaelastrasz le Corrompu",
      "Seigneur des couvées Lanistaire",
      "Gueule-de-feu",
      "Rochébène",
      "Flamegor",
      "Chromaggus", 
      "Nefarian",
    },
    AQ = {
      "Le prophète Skeram",
      "Garde de guerre Sartura",
      "Fankriss l'Inflexible",
      "Princesse Huhuran",
      "Empereurs Jumeaux",
      "C'Thun", 
      "Trio d'insectes",
      "Viscidus",
      "Ouro",
    },
    NAXX = {
      "Anub'Rekhan",
      "Grande Veuve Faerlina",
      "Maexxna",
      "Noth le Porte-peste",
      "Heigan l'Impur",
      "Horreb",
      "Instructor Razuvious",
      "Gothik the Harvester",
      "Les quatre Cavaliers",
      "Le recousu",
      "Grobbulus",
      "Gluth",
      "Thaddius",
      "Sapphiron",
      "Kel'Thuzad",
    },
    ZG = {
      "Seigneur sanglant Mandokir",
      "Gahz'ranka",
      "Hakkar",
      "Grand Prêtre Thekal",
      "Grand Prêtre Venoxis",
      "Grande Prêtresse Arlokk",
      "Grande Prêtresse Jeklik",
      "Jin'do le Maléficieur",
      "Grande Prêtresse Mar'li",
      "Folie mojo gurubashi",
    },
    AQ20 = {
      "Ayamiss le Chasseur",
      "Buru Grandgosier",
      "Général Rajaxx",
      "Kurinnaxx",
      "Moam",
      "Ossirian l'Intouché",
    },
    ONYXIA = {
      "Onyxia"
    },
    WORLD = {
      "Azuregos",
      "Seigneur Kazzak",
      "Emeriss",
      "Léthon",
      "Ysondre",
      "Taerar",
    }
  }
  
  core.ZoneList = {
    "Cœur du Magma",
    "Repaire de l'Aile noire",
    "Temple d'Ahn'Qiraj",
    "Naxxramas",
    "Zul'Gurub",
    "Ruines d'Ahn'Qiraj",
    "Repaire d'Onyxia",
    "Boss Mondial",
  }

  core.L = {
    ADD = "Ajouter",
    ADDED = "Ajoutée",
    ADDGUILDCONFIRM = "Êtes-vous sûr de vouloir ajouter les membres de la guilde qui sont gradés",
    ADDGUILDDKPTABLE = "Ajouter les guildeux dans la table DKP",
    ADDGUILDDKPTABLETT = "Ajoute les membres de la guilde ayant le grade sélectionné dans la table DKP, s'il n'y sont pas déjà.",
    ADDGUILDMEMBERS = "Ajouter les guildeux",
    ADDNEGTTDESC = "Appliquer le déclin aux membres endettés également. La dette sera réduite du pourcentage ci-dessus.",
    ADDNEGTTWARN = "N'affecte que les membres endettés.",
    ADDNEGVALUES = "Appliquer aux valeurs négatives",
    ADDRAIDMEMBERS = "Ajouter les raideurs",
    ADDRAIDMEMBERSCONFIRM = "Êtes-vous sûr de vouloir ajouter les membres du raid à la table DKP ?",
    ADDRAIDMEMBERSTTDESC = "Ajoute les membres du raid (ou groupe) qui sont dans la guilde dans la table DKP, s'il n'y sont pas déjà.", --TODO remove the "in guild" qualifier
    ADDREMDKPTABLEENTRIES = "Ajouter / Supprimer des entrées à la table DKP",
    ADDTARGET = "Ajouter la cible",
    ADDTARGETTODKPTABLE = "Ajouter la cible à la table DKP",
    ADDTARGETTTDESC = "Ajoute le joueur ciblé à la table DKP. Ne nécessite pas qu'il soit dans votre guilde.",
    ADDTOMAXROLL = "Ajouter au jet maximum",
    ADDTOMAXROLLTTDESC = "Ajoute une valeur prédéterminée au jet maximum.",
    ADDTOMAXROLLTTWARN = "Exemple : si vous voulez que le jet maximum de vos joueurs soit de 'DKP + 500' avec une plage de '1 - MaxDKP' définie ci-dessus, un joueur avec 80 DKP devrait /random 1-580.",
    ADDTOSTANDBY = "Ajouter les joueurs sélectionnés au banc",
    ADJUSTDESC = [=[Sélectionnez des entrées à gauche (Clic, Maj/Ctrl + Clic pour plusieurs joueurs) ou cliquez sur "Sélectionner les visibles" ci-dessous et entrez le montant à ajuster.

    L'affichage peut être ajusté avec "Afficher le raid uniquement" ci-dessous ou dans l'onglet "Filtres".]=],
    ADJUSTDKP = "Ajuster les DKP",
    ADJUSTDKPTTDESC = "Appliquer l'ajustement ci-dessus à toutes les entrées sélectionnées dans la table DKP.",
    ADJUSTDKPTTWARN = "Cet ajustement sera diffusé à tous les joueurs en ligne de votre guilde.",
    ALL = "tout",
    ALLCLASSES = "Toutes les classes",
    ALLOWNEGATIVEBIDDERS = "Autoriser les endettés à enchérir",
    ALLOWNEGATIVEBIDTTDESC = "Permet à un joueur d'enchérir si son solde DKP est actuellement négatif.",
    ALLTABLES = "Toutes vos tables sont actuellement",
    ALREADYASSIGNED = "Cet objet est déjà attribué à ce joueur.",
    ALSOWONBY = "Également gagné par",
    AMONG = "parmi",
    ANDCHARGEITTO = "et le charger à",
    ANNOUNCEAWARD = "Annoncer en guilde",
    ANNOUNCEAWARDTTDESC = "Si cette option est sélectionnée, vous annoncerez également les gains d'objet dans le canal guilde.",
    ANNOUNCEBID = "Annoncer le premier",
    ANNOUNCEBIDTTDESC = "Annoncer chaque fois qu'un nouvel enchérisseur prend l'offre la plus élevée",
    ANTISNIPE = "Anti-Snipe",
    ANTISNIPETTDESC = "Nombre de secondes auquel la durée d'enchère est étendue si une offre est reçue alors qu'il reste moins de 10 secondes.",
    ANTISNIPETTWARN = "Régler sur 0 pour désactiver l'anti-snipe.",
    ANNOUNCEINRAIDWARNING = "Annoncer en /ar",
    ANNOUNCEINRAIDWARNINGDESC = "Si coché, l'annonce de premier enchérisseur sera faite en canal Avertissement raid au lieu du canal raid",
    APPDECAYTTDESC = "Pourcentage de DKP perdu par chaque entrée par semaine. Doit être un nombre positif. Si \"Entrées sélectionnées uniquement\" n'est pas sélectionné ci-dessous, il s'appliquera à toutes les entrées.",
    APPDECAYTTWARN = "Attention: Ne peut pas être annulé.",
    APPLYDECAY = "Appliquer le déclin",
    AREYOUSURE = "Êtes-vous sûr de vouloir donner",
    AREYOUSUREBROADCAST = "Êtes-vous sûr de vouloir diffuser les paramètres du mode DKP ?",
    AREYOUSUREREASSIGN = "Êtes-vous sûr de vouloir réaffecter",
    ARTIFICIALINFLATION = "Inflation artificielle",
    ARTINFLATTTDESC = "Points à donner à chaque joueur SUR LE DKP divisé et réparti entre eux. Cette valeur est ajoutée à leur DKP gagné APRÈS que la valeur mise en banque soit divisée.",
    AUTOAWARD = "Prix ​​Auto DKP",
    AUTOAWARDTTDESC = "Attribue automatiquement des DKP de Boss tué (réglés dans l'onglet Options) lorsqu'un boss est tué. Seul le Chef de Raid distribuera ces points. Le raid doit être en cours (via l'onglet Ajuster les DKP).",
    AUTOCOMBATLOG = "Journal de combat automatique",
    AUTOCOMBATLOGTTDESC = "Active automatiquement /combatlog lorsque vous êtes dans un raid et que vous entrez dans une zone de raid ou entrez dans un combat avec un boss de raid.",
    AUTOCOMBATLOGTTWARN = "Vous devez toujours activer manuellement la journalisation de combat avancée dans Système > Réseau (si vous ne l'avez pas déjà fait).",
    AUTOOPEN = "Ouverture auto. de la fenêtre d'enchère",
    AUTOOPENTTDESC = "Lorsque cette case est cochée, la fenêtre d'enchères s'ouvre automatiquement à l'ouverture d'une enchère. Si cette case n'est pas cochée, vous devrez l'ouvrir manuellement avec \"/dkp bid\".",
    DECREASEDISENCHANT = "Diminuer la valeur de désenchantement",
    DECREASEDISENCHANTTTDESC = "Diminue la valeur de désenchantement de moitié pour chaque désenchantement après 3 désenchantements, jusqu'à un minimum de 5 DKP",
    AWARDBONUS = "Prime de présence",
    AWARDBONUSTTDESC = "Quantité de DKP à donner au raid après chaque période temporelle.",
    AWARDEDBY = "Attribué par:",
    AWARDINTERVAL = "Période de prime",
    AWARDINTERVALTTDESC = "Intervalle de temps (en minutes) entre chaque attribution de DKP à l’ensemble du raid.",
    AWARDINTERVALTTWARN = "Par exemple, si vous entrez 60, le raid (et le banc, si coché ci-dessous) reçoit le montant en DKP indiqué dans le champ \"Prime\" ci-dessus, toutes les heures.",
    AWARDITEM = "Attribuer",
    AWARDITEMTO = "Attribuer l'objet à",
    AWARDWARNING = "La commande award a été modifiée en / dkp award [lien de l’article].",
    BALANCE = "Équilibre",
    BCASTCOMPLETED = "Toutes les diffusions sont terminées.",
    BCASTDKPHIST = "Diffusion de l'historique DKP",
    BCASTDKPHISTBTN = "Diffuser l'historique DKP",
    BCASTDKPHISTCONF = "Êtes-vous sûr de vouloir diffuser votre historique DKP ?",
    BCASTDKPTABLEBTN = "Diffuser la table DKP",
    BCASTLOOTHIST = "Diffuser l'historique de butin",
    BCASTLOOTHISTBTN = "Diffuser l'historique de butin",
    BCASTLOOTTABLECONF = "Êtes-vous sûr de vouloir diffuser votre historique de butin ?",
    BCASTMAXBIDCONFIRM = "Êtes-vous sûr de vouloir diffuser vos paramètres d'enchères maximales à tous les officiers ?",
    BCASTMINBIDCONFIRM = "Êtes-vous sûr de vouloir diffuser vos paramètres d'enchères minimum à tous les officiers ?",
    BCASTVALUES = "Diffuser",
    BCASTVALUESTTDESC = "Diffuser les valeurs minimales des enchères ci-dessus à tous les officiers. Cela diffusera également toutes les valeurs personnalisées définies pour des éléments spécifiques dans la fenêtre d'enchère.",
    BCASTVALUESTTWARN = "Les valeurs actuelles ne seront pas écrasées. La réception de cette diffusion mettra à jour les valeurs déjà définies ou ajoutera des valeurs inexistantes. Toutes les valeurs qu'ils peuvent avoir et qui ne sont pas envoyées resteront inchangées.",
    BEGINSYNC = "Synchroniser les tables DKP",
    BELT = "Ceinture",
    BESTPRACTICES = "",
    BID = "Offre",
    BIDACCEPTEDFILTER = "Votre offre a été acceptée.",
    BIDCANCELLED = "Votre offre a été annulée.",
    BIDDENIEDEXCEEDMAX = "Offre refusée ! Votre enchère a dépassé la valeur de l'enchère maximum de",
    BIDDENIEDFILTER = "Offre refusée !",
    BIDDENIEDINVALID = "Offre refusée ! Enchère reçue non valide.",
    BIDDENIEDMINBID = "Offre refusée ! En dessous de l'enchère minimum de",
    BIDDENIEDNEGATIVE = "Offre refusée ! Votre DKP est négatif",
    BIDDENIEDNOVALUE = "Offre refusée ! Aucune valeur donnée pour l'enchère.",
    BIDDENIEDONLYHAVE = "Offre refusée ! Vous avez seulement",
    BIDDINGCLOSED = "Enchère fermée !",
    BIDEQUALORLESS = "Vous avez déjà une offre égale ou inférieure à cette offre.",
    BIDHELP = "Enchérir sur l'objet en cours lorsque l'enchère est ouverte.",
    BIDMETHOD = "Méthode d'enchère",
    BIDS = "Les offres",
    BIDTIMER = "Durée",
    BIDTIMERDEFAULTTTDESC = "Durée durant laquelle l’enchère restera ouverte par défaut, en secondes.",
    BIDTIMERTTDESC = "Durée durant laquelle l’enchère restera ouverte, en secondes.",
    BIDTIMERTTWARN = "La valeur par défaut peut être définie dans l'onglet Options.",
    BIDWASACCEPTED = "Offre acceptée.",
    BIDWHISPARENOW = "Les chuchotements sont maintenant",
    BLOCKOODBROADCAST = "Vous ne pouvez pas diffuser de tableaux obsolètes. Cela entraînerait une perte de données irrécupérable. Si vous êtes absolument certain de disposer des données les plus récentes, la suppression de l’étiquette de la note publique du chef de guilde résoudra ce problème.",
    BONUS = "Prime",
    BONUSAWARDED = "Prime attribuée",
    BOOTS = "Bottes",
    BOSS = "Boss",
    BOSSKILLBONUS = "Boss éliminé",
    BOSSKILLBONUSTTDESC = "Prime accordée pour avoir éliminé un Boss.",
    BRACERS = "Brassards",
    BROADCASTBIDS = "Diffuser les offres",
    BROADCASTBIDSTTDESC = "Une fois activé, toutes les personnes du raid verront toutes les offres soumises dans leur interface d'enchères. Désactivez-la si vous ne voulez pas que les joueurs voient les enchères des autres.",
    BROADCASTDKPTABLECONF = "Êtes-vous sûr de vouloir diffuser toutes les tables ? Cela ne fusionne pas votre table avec celle des autres. Votre table écrasera complètement celles de tous les membres de votre guilde.",
    BROADCASTSETTINGS = "Diffuser les paramètres",
    BROADCASTSETTTDESC = "Diffuse tous les paramètres liés aux DKP, y compris les paramètres de mode DKP ci-dessus, ainsi que les valeurs des objets et les valeurs des prime (définies dans Options).",
    CANCEL = "Annuler",
    CANCELBID = "Annuler l'enchère",
    CANTCANCELROLL = "Vous n'êtes pas autorisé à annuler un jet.",
    CASTERDPS = "DPS Magie",
    CHANGEDGUILDS = "Vous semblez avoir rejoint une nouvelle guilde. Toutes les données de votre guilde précédente ont été effacées pour éviter la corruption des données.",
    CHEST = "Torse",
    CLASS = "Classe",
    CLASSFILTER = "Filtres de classe",
    CLEARBIDWINDOW = "Vider la fenêtre",
    CLEARBIDWINDOWTTDESC = "Efface toutes les informations sur les objets et les offres soumises de la fenêtre.",
    CLEARSTANDBY = "Vider le banc",
    CLICKQUERYGUILD = "Cliquez ici pour ouvrir l'interface de diffusion. Cela récupérera également les informations de spécialisation et de rôle des joueurs en ligne.",
    CLOAK = "Cape",
    CLOSE = "Fermer",
    CLOSEDBIDINPROGRESS = "Fenêtre d'enchères fermée avec une enchère en cours ! Saisissez '/dkp bid' pour réouvrir l’enchère en cours.",
    COMMANDCHANNELS = "Canaux de commande",
    COMMANDCHANNELSTTDESC = "Sélectionnez les canaux de dialogue sur lesquels vous souhaitez recevoir les commandes. Un chuchotement de confirmation sera envoyé à toutes les commandes reçues.",
    CONFAWARD = "Confirmer l'attribution",
    CONFIRM = "Confirmer",
    CONFIRMADDTARGET = "Êtes-vous sûr de vouloir ajouter",
    CONFIRMAWARD = "Êtes-vous sûr de vouloir attribuer",
    CONFIRMDECAY = "Êtes-vous sûr de vouloir appliquer un déclin à",
    CONFIRMDELETEENTRY1 = "Êtes-vous sûr de vouloir supprimer l'entrée",
    CONFIRMMIGRATE = "Êtes-vous certain de vouloir devenir l'officier responsable de la migration ? Cette opération est irréversible.",
    CONFIRMREMOVESELECT = "Êtes-vous sûr de vouloir supprimer",
    CONFIRMWHITELIST = "Êtes-vous sûr de vouloir ajouter les joueurs sélectionnés à la liste blanche ?",
    CONFIRMWHITELISTCLEAR = "Êtes-vous sûr de vouloir effacer la liste blanche ?",
    CONGRATS = "Félicitations à ",
    CONTACTOFFICER = "Veuillez contacter un officier indiqué ci-dessus en tant que \"À jour\" pour que vos tables soient mises à jour.",
    CONTINUERAID = "Reprendre le raid",
    CORRECTINGERROR = "Correction",
    COSTAUTOUPDATE = "Mode de mise à jour automatique des prix",
    COSTAUTOUPDATETTDESC = "Sélectionner le mode de mise à jour automatique des prix après une enchère.\n\n|CFFFF0000Enchère la plus haute|r: Le prix de l'objet en bas de la fenêtre d'enchère correspondera à l'enchère la plus haute. \n\n|CFFFF0000Deuxième enchère la plus haute|r: Le prix de l'objet en bas de la fenêtre d'enchère correspondera à la deuxième enchère la plus haute (ou la plus haute s'il n'y en a qu'une).\n\n|CFFFF0000Deuxième ou minimum|r: Le prix de l'objet en bas de la fenêtre d'enchère correspondera à la deuxième enchère la plus haute (ou à l'enchère s'il n'y en a qu'une). \n\nLe prix est toujours modifiable à la volée.",
    COSTAUTOUPDATEVALUE = "Prix automatique",
    CREATEDMAINTAIN = "créé et maintenu par",
    CREATERAIDTIMER = "Crée une minuterie de raid (officiers uniquement) (par exemple: '/dkp timer 120 Pause Pizza !')",
    CURRENTLYHAS = "a actuellement",
    CURRENTLYSYNCING = "Synchronisation des tables en cours. Veuillez attendre la fin de la synchronisation pour continuer.",
    CURRNOTINGUILD = "Vous n'êtes pas actuellement dans une guilde. Le statut DKP ne peut pas être récupéré.",
    CUSTOM = "Personnalisé",
    CUSTOMMAXBID = "Enchère maximale personnalisée",
    CUSTOMMAXBIDTTDESC = "Vous avez défini une enchère maximale personnalisée pour cet objet. Décochez cette case pour utiliser l'enchère maximale standard pour ce type d'objet (définie dans l'onglet Options).",
    CUSTOMMAXBIDTTWARN = "Ouvrir l'enchère avec cette case non cochée supprimera l'enchère maximale personnalisée de la base de données.",
    CUSTOMMINBID = "Enchère minimale personnalisée",
    CUSTOMMINBIDTTDESC = "Vous avez défini une enchère minimale personnalisée pour cet objet. Décochez cette case pour utiliser l'enchère minimale standard pour ce type d'objet (défini dans l'onglet Options).",
    CUSTOMMINBIDTTWARN = "Ouvrir l'enchère avec cette case non cochée supprimera l'enchère minimale personnalisée de la base de données.",
    DAY = "jour",
    DAYS = "jours",
    DECAYAMOUNT = "Déclin",
    DECAYPERCENTAGE = "Pourcentage de déclin",
    DECAYPERCENTAGETTDESC = "Pourcentage de réduction de toutes les valeurs de DKP par déclin.",
    DECAYPERCENTAGETTWARN = "Nombre positif uniquement.",
    DECLINELOWBIDS = "Refuser les offres basses",
    DECLINELOWBIDSTTDESC = "Refuser automatiquement toute offre soumise si elle est égale ou inférieure à l'offre la plus élevée en cours.",
    DEFAULTDKPAWARDVALUES = "Valeurs par défaut des primes DKP",
    DEFAULTITEMCOSTS = "Prix par défaut",
    DEFAULTMAXBIDVALUES = "Enchère maximale par défaut",
    DEFAULTMINBIDVALUES = "Enchère minimale par défaut",
    DEFAULTSETSAVED = "Paramètres par défaut enregistrés.",
    DEFAULTSETTINGS = "Paramètres par défaut",
    DELETEDBY = "Entrée supprimée par :",
    DELETEDENTRY = "Entrées supprimées",
    DELETEDKPENTRY = "Supprimer l'entrée DKP",
    DELETEENTRYREFUNDCONF = "Les DKP de cette entrée seront remboursés / repris à chaque joueur concerné.",
    DELETETABLES = "Supprimer des tables",
    DISABLED = "désactivé",
    DISTRIBUTEALLDKPCONF = "Distribuer des DKP à tous les joueurs du raid ?",
    DISTRIBUTEDKP = "Distribuer des DKP",
    DISTRUBUTEBANKED = "Distribuez le DKP en banque à tous les membres du raid de manière égale après le pillage du boss actuel.",
    DKP = "DKP",
    DKPADJUST = "Ajustement DKP",
    DKPADJUSTBY = "DKP ajusté par",
    DKPAVAILABLE = "DKP disponible",
    DKPAWARDHELP = "Attribuer manuellement un article (officiers uniquement)",
    DKPBROADCASTED = "Base de données DKP diffusée",
    DKPCMDHELP = "Renvoie votre DKP actuel (ou DKP de <nom du joueur>)",
    DKPDATAUPDATEDBY = "Base de données DKP mise à jour par",
    DKPENTRIESBY = "Entrées DKP par",
    DKPEXPORTHELP = "Ouvre une fenêtre pour exporter toutes les informations DKP au format HTML, CSV ou XML. (Plusieurs implémentations d'exportation à venir)",
    DKPHISTCASTCOMP = "La diffusion de l'historique DKP est terminée",
    DKPHISTLIMITTTDESC = "Nombre maximal d'entrées de l'historique DKP stockées.",
    DKPHISTLIMITTTWARN = "Avertissement: Si vous réduisez ce nombre en deçà du nombre d'entrées actuellement stockées, les plus anciennes seront supprimées pour respecter la limite.",
    DKPHISTORY = "Historique DKP",
    DKPHISTORYLIMIT = "Limite d'historique DKP",
    DKPHISTORYUPDATECOMP = "La mise à jour de l'historique DKP est terminée.",
    DKPHISTRECORDS = "Historique DKP",
    DKPHISTUPDATEPROG = "Mise à jour de l'historique DKP en cours",
    DKPLAUNCH = "Lance la fenêtre DKP",
    DKPLOCKOUT = "Affiche la prochaine réinitialisation pour chaque taille de raid (lock-out de 3, 5 et 7 jours)",
    DKPMAXBID = "Enchère maximale DKP",
    DKPMINBID = "Enchère minimale DKP",
    DKPMODES = "Modes DKP",
    DKPMODESENTCONF = "Paramètres du mode DKP envoyés",
    DKPMODESFOOTER = "Si des modifications sont apportées à cette fenêtre, votre interface utilisateur | cffff0000MUST |r devra être rechargée. Vous recevrez des erreurs si un rechargement n'est pas effectué. Vous serez invité à le faire à la fermeture de la fenêtre.",
    DKPMODESHELP = "Ouvre la fenêtre des modes DKP (officiers uniquement)",
    DKPMODESTTDESC = "Sélectionner le mode DKP à utiliser dans la fenêtre d'enchères. Les descriptions de mode seront affichées au dessus lors de la sélection. Rechargez après avoir sélectionné votre mode.",
    DKPMODESTTDESC2 = "Configurer le mode de système DKP que vous utiliserez. Chaque mode est fortement paramétrable.",
    DKPMODESTTWARN = "Votre interface doit être rechargée si des paramètres sont modifiés. Vous serez invité à le faire lors de la fermeture. Sinon, cela entraînera des erreurs.",
    DKPPRICE = "Prix ​​DKP",
    DKPRESETPOS = "Réinitialise la taille et position de la fenêtre DKP",
    DKPROUNDING = "Arrondi DKP",
    DKPROUNDINGTTDESC = "Définissez le nombre de décimales que vous souhaitez utiliser dans votre système DKP. Zéro signifie des entiers arrondis (sans décimales)",
    DKPSETTINGS = "Primes DKP",
    DKPSTATUS = "Statut DKP",
    DKPTOFOLLOWING = "DKP aux joueurs suivants",
    DKPVALUES = "Valeurs DKP",
    DKPWASACCEPTED = "DKP a été accepté",
    DONTSHOW = "Ne plus montrer pour cette version.",
    ELEMENTAL = "Elémentaire",
    ENABLED = "Activée",
    ENDBIDDING = "Fin des enchères",
    ENDCURRAIDCONFIRM = "Êtes-vous sûr de vouloir mettre fin au raid ?",
    ENDRAID = "Fin du raid",
    ENHANCEMENT = "Amélioration",
    ENTEROTHERREASONHERE = "Entrez un autre motif ici",
    ENTRIESSELECTED = "Entrées sélectionnées",
    ENTRIESSHOWN = "Entrées affichées",
    ENTRYSELECTED = "Entrée sélectionnée",
    ERRANTINPROGRESS = "Contrôle des entrées errantes en cours. Veuillez patienter...",
    ERROR = "Erreur",
    ERRORPROCESSING = "Erreur de traitement de la commande",
    EXPECTEDROLL = "Jet attendu",
    FERAL = "Combat Farouche",
    FILTERS = "Filtres",
    FIRSTBIDDER = "Enchère la plus haute",
    FIRSTKILL = "Premier meurtre",
    FOR = "pour",
    FORBACKSLOT = "pour les capes.",
    FORCHESTSLOT = "pour les torses.",
    FORFEETSLOT = "pour les bottes.",
    FORFINGERSLOT = "pour les anneaux.",
    FORHANDSLOT = "pour les gants.",
    FORHEADSLOT = "pour les casques.",
    FORLEGSLOT = "pour les jambières.",
    FORNECKSLOT = "pour les colliers.",
    FOROFFHANDSLOT = "pour les boucliers et mains-gauches.",
    FORONEHANDSLOT = "pour les armes à une main.",
    FOROTHERSLOT = "pour tous les autres objets qui n'entrent pas dans les catégories ci-dessus (têtes, cœurs, feuille de chasseur, etc.)",
    FORPLAYERS = "pour les joueurs suivants",
    FORRANGESLOT = "pour les armes à distance (arcs, pistolets, baguettes) et reliques.",
    FORREASON = "pour le motif suivante : ",
    FORSHOULDERSLOT = "pour les épaulières.",
    FORTRINKETSLOT = "pour les bijoux.",
    FORTWOHANDSLOT = "pour les armes à deux mains.",
    FORWAISTSLOT = "pour les ceintures.",
    FORWRISTSLOT = "pour les brassards.",
    FROMSTANDBYLIST = "du banc",
    GENDKPHIST = "Générer l'historique DKP",
    GENDKPTABLE = "Générer une table DKP",
    GENLOOTHIST = "Générer l'historique de butin",
    GIVEENDBONUS = "Donner la prime de fin",
    GIVEENDBONUSTTDESC = "Sélectionnez cette option pour attribuer la prime \"Fin du raid\" au raid (et au banc, si coché ci-dessous) lorsque vous terminez le raid.",
    GIVEONTIMEBONUS = "Donner la prime de départ",
    GIVEONTIMETTDESC = "Sélectionnez cette option pour attribuer la prime \"À l'heure\" au raid (et au banc, si coché ci-dessous) lorsque vous commencez le raid.",
    GUILD = "Guilde",
    HANDS = "Mains",
    HEAD = "Tête",
    HEALER = "Soigneur",
    HELPINFO = "Affiche les informations d'aide",
    HIDDEN = "caché",
    HIDEBIDTIMER = "Masquer la minuterie d'enchères",
    HIGHESTBID = "Offre la plus élevée",
    HOLY = "Sacré",
    HOUR = "heure",
    HOURS = "heures",
    IN = "dans",
    INCLUDENAME = "Inclure le joueur",
    INCLUDENAMETTDESC = "Inclut le nom du joueur qui a soumis l'offre la plus élevée en cours lors de l'annonce du plus offrant.",
    INCLUDESBYTTDESC = "Inclut les joueurs sur le banc lors de l'attribution automatique des DKP de Boss éliminé activé ci-dessus.",
    INCLUDESBYTTWARN = "Si l'inscription au banc est active, le DKP est attribué immédiatement au raid, alors que le banc recevera ses DKP à la fin la période d'inscription",
    INCLUDESTANDBY = "Inclure le banc",
    INCLUDESTANDBYLIST = "Inclure le banc",
    INCLUDESTANDBYTTDESC = "Cocher cette case inclura le banc dans toutes les distributions de DKP automatiques.",
    INCLUDESTANDBYTTWARN = "Créez un banc de remplaçants en sélectionnant des joueurs de la table DKP qui ne font pas partie du raid, en cliquant avec le bouton droit de la souris sur 'Gérer le banc > Ajouter les joueurs sélectionnés au banc'.",
    INCREMENTINVALIDWARN = "La période sélectionnée est invalide.",
    INCSTANDBYLISTTTDESC = "Inclut les joueurs du banc dans la distribution.",
    INCSTANDBYLISTTTWARN = "Cela donnera des valeurs plus petites aux joueurs du raid.",
    INFLATION = "Inflation",
    INITRAID = "Initialiser le Raid",
    INITRAIDTTDESC = "Commence le raid et attribue les DKP périodiquement. Tous les officiers peuvent le faire, mais seul le chef du raid <traduction impossible: only the raid leader will give the DKP award the checked conditions are met>.",
    INITRAIDTTWARN = "Ceci est diffusé à tous les officiers du raid. Chaque officier aura un chronomètre, mais SEUL le chef de raid donnera les primes. Si un événement survient (déconnecté, rechargement, etc.) entraînant la perte du chronomètre, donnez le chef de raid à un autre officier dont le chronomètre est toujours en cours d'exécution pour éviter toute interruption.",
    INPARTYRAID = "En groupe / raid",
    INTEGER = "Entier",
    INTERVAL = "Période",
    INVALIDBOSSNAME = "Nom du boss invalide",
    INVALIDITEMCOST = "Impossible d'attribuer l'objet. Coût de l'objet invalide",
    INVALIDITEMLINK = "Impossible d'attribuer l'objet. Lien d'objet invalide",
    INVALIDMINBIDENTRY = "Entrée d'offre minimale invalide à",
    INVALIDOPTIONENTRY = "Entrée d'options invalide à",
    INVALIDPLAYER = "Joueur invalide. Vous n'êtes pas répertorié dans la table DKP.",
    INVALIDROLLPARAM = "Vous avez défini un paramètre de jet invalide. Veuillez vérifier vos paramètres.",
    INVALIDROLLRANGE = "Vous avez défini une plage de jet invalide. Veuillez vérifier vos paramètres.",
    INVALIDTARGETPLAYER = "Impossible d'attribuer l'objet. Joueur cible invalide",
    INVALIDTIMER = "Minuterie invalide",
    INVITE = "Inviter",
    INVITESELECTED = "Inviter les personnes sélectionnées au raid",
    INZONEONLY = "Dans la même zone",
    INZONEONLYTTDESC = "Cela n'accordera le raid DKP qu'aux joueurs qui se trouvent dans la même zone que vous. (À utiliser avec attribution automatique, minuterie de raid et distribution à somme nulle)",
    ITEM = "Objet",
    ITEMS = "Objets",
    ITEMCOST = "Prix",
    ITEMCOSTTTDESC = "DKP dépensés par le joueur pour acheter l'objet.",
    ITEMCOSTTYPES = "Prix du type d'objet",
    ITEMCOSTTYPESTTDESC = [=[Sélectionnez le type de valeur utilisé pour les prix des objets: entier ou pourcentage. Ces valeurs sont définies dans l’onglet "Options". 

    |CFFFF0000Entier|r: les prix des objets sont des entiers (les décimales sont arrondies à la décimale indiquée par "Arrondi DKP" ci-dessous). ex: 100 DKP. 

    |CFFFF0000Pour cent|r: le prix des objets correspond à un pourcentage du total des DKP des joueurs gagnants. ex: le joueur a 1000 DKP, le prix de l'objet est de 20%. Par conséquent, le coût d'objet est de 200 DKP pour ce joueur.]=],
    LEGS = "Jambes",
    LIFETIMEEARNED = "Vie gagné",
    LIFETIMESPENT = "Toute la vie passée",
    LOAD = "Charge",
    LOAD50MORE = "Charger %d de plus...",
    LOADED = "Chargé",
    LOGBIDS = "Journal des enchères / jets",
    LOGBIDSTTDESC = "Cela enregistrera et inclura les enchères / jets sur l'info-bulle de chaque objet gagné dans l'onglet Historique du butin.",
    LOOTBANKED = "Butin en banque",
    LOOTHISTCASTCOMP = "Diffusion de l'historique de butin terminée",
    LOOTHISTINST1 = [=[Shift + Cliquez pour lier l'élément
    Alt + Cliquer pour lier la ligne]=],
    LOOTHISTINST2 = "Clic droit pour modifier une entrée",
    LOOTHISTINST3 = "Clic droit pour supprimer une entrée",
    LOOTHISTLIMITTTDESC = "Nombre maximal d'entrées de l'historique de butin stockées.",
    LOOTHISTLIMITTTWARN = "Avertissement: Si vous réduisez ce nombre en deçà du nombre d'entrées actuellement stockées, les plus anciennes seront supprimées pour respecter la limite.",
    LOOTHISTORY = "Historique de butin",
    LOOTHISTORYLIMIT = "Limite d'historique de butin",
    LOOTHISTORYUPDATECOMP = "Mise à jour de l'historique de butin terminée.",
    LOOTHISTRECORDS = "entrées d'historique de butin et",
    LOOTHISTUPDATEPROG = "Mise à jour de l'historique de butin en cours",
    MAINGUISIZE = "Taille de l'interface",
    MANAGE = "Gérer",
    MANAGECORELIST = "Gérer la liste des raideurs",
    MANAGEDKP = "Gérer les entrées DKP",
    MANAGELISTS = "Gérer les listes",
    MANAGESTANDBY = "Gérer le banc",
    MANUALLYDENIED = "a été refusé.",
    MAX = "Max",
    MAXBIDBEHAVIOR = "Comportement du bouton d'enchère MAX",
    MAXBIDBEHAVIORMAXDKP = "Max DKP",
    MAXBIDBEHAVIORMAXITEMVALUE = "Valeur maximale de l'objet",
    MAXBIDBEHAVIORMIN = "Min(Max DKP, Valeur maximale de l'objet)",
    MAXBIDBEHAVIORTTDESC = "Sélectionnez le comportement du bouton d'enchère MAX lors d'une enchère.\n\n|CFFFF0000Max DKP|r: Cela définira la valeur de l'enchère aux DKP actuels du joueur.\n\n|CFFFF0000Valeur maximale de l'objet|r: Cela définira la valeur de l'enchère à la valeur maximale de l'objet. \n\n|CFFFF0000Min(Max DKP, Valeur maximale de l'article)|r: Cela définira la valeur de l'enchère à la plus petite des deux autres options.",
    MAXBIDTTDESC = "Valeur d'enchère maximale qui sera acceptée.",
    MAXBIDTTEXT = "Si vous entrez une valeur autre que celle définie dans Options, cette valeur personnalisée sera stockée pour cet objet spécifique.",
    MAXBIDTTWARN = "Les valeurs par défaut peuvent être définies dans l'onglet Options.",
    MAXBIDVALUESHEAD = "Valeurs maximales des enchères",
    MAXBIDVALUESSENT = "Valeurs maximales des enchères envoyées",
    MAXGTMIN = "La valeur maximale doit être >= au minimum ou 0 !",
    MAXIMUMBID = "Enchère maximum",
    MAXIMUMBIDTTDESC = "Enchère maximum autorisée. Si un joueur tente d'enchérir au dessus de cette valeur, son enchère sera refusée. Réglez sur 0 si vous ne souhaitez pas avoir un max.",
    MAXIMUMROLL = "Jet maximum",
    MAXIMUMROLLTTDESC = "Définissez le jet maximum à utiliser. Laissez le champ vide pour utiliser le maximum de DKP du joueur en tant que jet maximal.",
    MAXIMUMROLLTTWARN = "Ne laisser vide seulement si \"Utiliser le pourcentage\" est décoché. Si cette case est cochée, utilisez 100%.",
    MELEEDPS = "DPS de mêlée",
    MIGRATE = "Migrer",
    MIGRATEINST1 = [=[|cffff0000IMPORTANT!!|r: Sauvegardez votre fichier de variables sauvegardé avant de continuer. Avec 2.0 vient un tout nouveau système de diffusion indexé. Cela nécessite que vos tables actuelles soient migrées avec de nouvelles valeurs. Cette migration est un processus unique pouvant être effectué UNIQUEMENT par UN SEUL officier. Sélectionnez le responsable avec les données les plus précises pour effectuer la migration. Tous les autres officiers seront bloqués et leurs données supprimées pour accepter la diffusion des nouvelles données de cet agent sélectionné. Cela évite les doublons. Une fois que TOUS les officiers ont reçu les nouvelles données, vous pouvez supprimer la balise {CommDKP = OFFICER_NAME} de la note publique des chefs de guilde. Il est absolument essentiel qu'un seul officier effectue la migration, sinon vous aurez des données en double et vos tables seront corrompues (le seul moyen de résoudre le problème consiste à faire en sorte que tous les officiers dont les tables sont corrompues se déconnectent et suppriment simultanément leurs fichiers de variables sauvegardés ou bien vous recevrez simplement les données corrompues à nouveau dès que vous vous connecterez). En outre, tous les membres doivent utiliser la version 2.0 ou ultérieure pour être compatibles. Les anciennes versions ne fonctionneront PAS.

    Cette fenêtre peut être rouverte avec "/dkp migrate".]=],
    MIGRATEINST2 = "%s a déjà effectué la migration. Sauvegardez immédiatement votre fichier de variables sauvegardé (WTF\\Account\\ACCOUNT_NAME\\SavedVariables\\CommunityDKP.lua), puis cliquez sur le bouton de suppression de tables ci-dessous. Si %s est en ligne, ils vous enverront automatiquement une synchronisation après le rechargement. Si ce n'est pas le cas, ils seront poussés lorsqu'ils se connecteront ou vous pourrez demander qu'ils poussent une synchronisation (pour ce faire, cliquez sur le bouton d'état de la table dans le coin inférieur gauche de l'interface graphique principale). Si des erreurs se produisent dans le processus de migration de votre guilde, supprimez la balise des officiers en migration de la note publique du chef de guilde et demandez à tous les officiers ayant participé à cette opération de supprimer leur fichier de variables sauvegardées corrompu et de le restaurer sur celui sauvegardé. Tout le monde doit le faire en même temps et ne pas se connecter (avec l'addon activé) jusqu'à ce que cela soit terminé. Toute personne en ligne avec des tables migrées transmettra automatiquement ces données dès que vous vous connecterez.",
    MIN = "Min",
    MINBIDDESCRIPTION = [=[Avec les valeurs d'enchères minimales, une valeur minimale est attribuée à tous les emplacements (ou articles individuels). Toute personne qui soumet une enchère doit enchérir à cette valeur ou à une valeur supérieure. 

    Ex: |cffa335ee|Hitem:16865::::::::120:577::::::|h[Breastplate of Might]|h|r tombe et a une enchère minimum de 50 DKP. Chaque joueur qui le souhaite envoie "!Bid 50" (ou plus) via l’un des canaux ouverts (sélectionné ci-dessous) sans dépasser son DKP disponible (sauf si le DKP inférieur à zéro est activé). Le joueur avec l'enchère la plus élevée gagne et se voit facturer soit la valeur minimale de DKP, soit la valeur que le deuxième enchérisseur a soumis. Lisez les info-bulles pour plus d'informations.]=],
    MINBIDTTDESC = "Valeur d'enchère minimum qui sera acceptée.",
    MINBIDTTEXT = "Si vous entrez une valeur autre que celle définie dans Options, cette valeur personnalisée sera stockée pour cet élément spécifique.",
    MINBIDTTWARN = "Les valeurs par défaut peuvent être définies dans l'onglet Options.",
    MINBIDVALUESHEAD = "Valeurs d'enchère minimales",
    MINBIDVALUESSENT = "Valeurs d'enchère minimum envoyées",
    MINIMUMBID = "Enchère minimum",
    MINIMUMROLL = "Jet minimum",
    MINIMUMROLLTTDESC = "Définissez le jet minimum à utiliser.",
    MINUTE = "minute",
    MINUTES = "minutes",
    MISCSETTINGS = "Réglages divers",
    CommDKPSCALESIZE = "Échelle de CommunityDKP",
    CommDKPSCALESIZETTDESC = "Échelle de la fenêtre CommunityDKP. Cliquez sur \"Enregistrer les paramètres\" pour modifier la taille afin de définir la valeur.",
    CommDKPSCALESIZETTWARN = "Peut nécessiter un /reload après l'enregistrement si un autre addon est utilisé pour modifier les échelles de l'interface utilisateur (ex. TukUI, ElvUI, etc.)",
    MORE = "plus",
    MORESECONDSTO = "plus de seconde (s) pour le faire.",
    MOVEBIDTIMER = "Déplacer la minuterie d'enchères",
    MOVEME = "Bouge-moi!",
    MULTIPLESELECT = "Sélections multiples",
    MUSTRELOADUI = "Vos paramètres de modes DKP ont changé et ne peuvent pas être exécutés tant que votre interface n'est pas rechargée. Recharger l'interface ?",
    NAMENOTFOUND = "Votre nom n'a pas été trouvé dans la base de données DKP.",
    NECK = "Cou",
    NEWBOSSKILLBONUS = "Prime de Boss éliminé (Première fois)",
    NEWBOSSKILLTTDESC = "Prime donnée pour la première élimination d'un boss, lors d'un raid de progression.",
    NEWHIGHBID = "L'offre la plus élevée est maintenant",
    NEWHIGHBIDDER = "Le plus offrant est maintenant",
    NEWHIGHROLL = "Le jet le plus élevé est maintenant",
    NEWHIGHROLLER = "La tête est prise par",
    NO = "Non",
    NOBIDINPROGRESS = "Aucune offre en cours",
    NOCORERAIDTEAM = "Il n'y a pas de joueurs dans votre équipe de base.",
    NOENTRIESRETURNED = "Aucun profil retourné",
    NOENTRIESSELECTED = "Aucune entrée sélectionnée.",
    NOFILTER = "Pas de filtre",
    NOGUILD = "Pas de guilde",
    NOITEMORITEMCOST = "Aucun coût d'objet et / ou objet pour enchérir !",
    NOMINBIDORITEM = "Aucune enchère minimum / maximum et / ou objet sur lequel enchérir!",
    NONE = "Aucun",
    NOOFFICERSONLINE = "Il n'y a actuellement aucun officier disponible pour se synchroniser. (Hors ligne ou récemment synchronisé)",
    NOPARTYORRAID = "Vous n'êtes pas dans un groupe ou un raid.",
    NOPERMISSION = "Vous n'êtes pas autorisé à accéder à cette fonctionnalité.",
    NOPLAYERINSTANDBY = "Il n'y a pas de joueurs sur le banc dans le groupe.",
    NOPLAYERSSELECTED = "Aucun joueur sélectionné pour transférer le butin.",
    NOPLAYERTARGETED = "Aucun joueur ciblé.",
    NOPOINTSTODISTRIBUTE = "Il n'y a pas de points à distribuer.",
    NORANKSELECTED = "Aucun grade n'est sélectionné.",
    NOROLEDETECTED = "Aucun rôle détecté",
    NOSPECREPORTED = "Aucune spécification signalée",
    NOTANOFFICER = "n'est pas un officier. Vous ne pouvez ajouter que des rangs disposant des autorisations \"Modifier la note du responsable\" dans les paramètres de guilde.",
    NOTETOOLONG = "La note publique des chefs de guilde était trop longue. Note tronquée pour s'adapter à l'horodatage de la table DKP. (31 caractères maximum)",
    NOTIFICATIONSLIKETHIS = "Des notifications comme celle-ci sont maintenant",
    NOTINGUILD = "Pas dans la guilde",
    NOTINRAID = "Vous n'êtes pas dans un raid.",
    NOTINRAIDFILTER = "Pas en raid",
    NOTINRAIDPARTY = "Vous n'êtes pas dans une soirée de raid.",
    NOTSUBMITTEDBID = "Vous n'avez pas soumis d'enchère.",
    NOWLOGGINGCOMBAT = "Enregistrement du journal de combat commencé.",
    OFF = "de",
    OFFHAND = "En main gauche",
    OFFHANDITEMS = "Articles en main gauche",
    OK = "D'accord",
    ON = "sur",
    ONEHANDED = "À une main",
    ONEHANDEDWEAPONS = "Armes à une main",
    ONETABLEOOD = "Une ou plusieurs de vos tables sont actuellement",
    ONLINE = "En ligne",
    ONLINEONLY = "En ligne seulement",
    ONLINEONLYTTDESC = "Cela n'accordera les DKP du raid qu'aux joueurs en ligne. (À utiliser avec attribution automatique, minuterie de raid et distribution à somme nulle)",
    ONLYONEROLLWARN = "Un seul jet peut être accepté !",
    ONLYPARTYRAID = "Groupe ou Raid seulement",
    ONTIMEBONUS = "Prime 'À l'heure'",
    ONTIMEBONUSTTDESC = "Prime donnée pour la présence au raid à l'heure.",
    OODDKPHISTORYDELETE = "a tenté de supprimer un élément d'un historique DKP obsolète. Cela peut causer des dommages irréversibles à votre historique. Voulez-vous accepter ?",
    OODDKPHISTORYENTRY = "a diffusé une entrée d'historique DKP obsolète. Cela peut causer des dommages irréversibles à votre historique. Voulez-vous accepter ?",
    OODDKPHISTORYTABLE = "a diffusé un historique DKP obsolète. Cela peut causer des dommages irréversibles à votre historique. Voulez-vous accepter ?",
    OODDKPTABLEBROADCAST = "a diffusé une table DKP obsolète. Cela peut causer des dommages irréversibles à votre historique. Voulez-vous accepter ?",
    OODLOGSYNC = "a diffusé une table d'historique de butin obsolète. Cela peut causer des dommages irréversibles à votre historique. Voulez-vous accepter ?",
    OODLOOTHISTORYDELETE = "a supprimé un élément de l'historique de butin obsolète. Cela pourrait entraîner la suppression du mauvais élément de votre historique. Voulez-vous accepter ?",
    OODLOOTTABLEITEM = "a tenté de mettre à jour un élément d'un historique de butin obsolète. Cela peut causer des dommages irréversibles à votre historique. Voulez-vous accepter ?",
    OPENAUCWINHELP = "Ouvre la fenêtre d'enchères avec l'élément lié (officiers uniquement)",
    OPENBIDWINDOWHELP = "Ouvre la fenêtre d'enchères",
    OPENCHANNELS = "Canaux ouverts",
    OPTIONS = "Les options",
    OR = "ou",
    ORABOVE = "ou au-dessus?",
    OTHER = "Autre",
    OTHERREASONVALIDATE = "Aucun autre - Motif sélectionné",
    OUTDATEMODIFYWARN = [=[Vous tentez de modifier une table DKP obsolète. Cela risquerait de corrompre par inadvertance les données des officiers disposant des tables les plus récentes.

    Êtes-vous sûr de vouloir faire cela?]=],
    OUTOFDATE = "périmé",
    OUTOFDATEANNOUNCE = "Votre version de CommunityDKP est obsolète. Veuillez mettre à jour Curse / Twitch ou WoWInterface pour vous assurer qu'il n'y a aucun problème de compatibilité.",
    PAUSERAID = "Interrompre le raid",
    PAUSERAIDTTDESC = "Ceci met en pause un chronomètre de raid si le chef décide que le chronomètre doit être arrêté pour les pauses.",
    PAUSERAIDTTWARN = "Peut être repris en cliquant sur \"Reprendre le raid\".",
    PERCENT = "Pourcent",
    PERCENTCOST = "Prix en pourcentage",
    PLAYER = "Joueur",
    PLAYERCOST = "[lien de l'objet]",
    PLAYERNAME = "nom du joueur",
    PLAYERNOTFOUND = "Ce joueur n'a pas été trouvé.",
    PLAYERREASONVALIDATE = "Aucun joueur ou raison sélectionné",
    PLAYERRECORDS = "entrées de joueur",
    PLAYERROLL = "Jet de joueur",
    PLAYERS = "joueur(s)",
    PLAYERSFORREASON = "joueurs pour la raison suivante : ",
    PLAYERVALIDATE = "Aucun joueur sélectionné",
    PLEASEUSENUMS = "Veuillez utiliser des chiffres.",
    PRICETAB = "Pricing", --TODO
    PLEASEVALIDATE = "Les entrées invalides ont été supprimées. Merci de valider vos tables. (Dans le menu contextuel clic droit sur la table DKP)",
    POINTS = "Points",
    POINTSTTDESC = "Entrez le montant de DKP à distribuer aux joueurs sélectionnés sur la table DKP. Les valeurs par défaut peuvent être modifiées dans l'onglet \"Options\" ci-dessous.",
    POINTSTTWARN = "Utilisez un nombre négatif pour retirer des DKP aux joueurs sélectionnés.",
    POPOUTTIMER = "Chronomètre de raid miniature",
    POPOUTTIMERDESC = "Affiche la minuterie de raid dans une fenêtre compacte séparée.",
    POSITIONRESET = "Réinitialisation de la position de la fenêtre",
    PROTECTION = "Protection",
    PURGECONFIRM = "Êtes-vous sûr de vouloir purger la table DKP ?",
    PURGELIST = "Purger la table DKP",
    PURGELISTTTDESC = "Purge la table DKP de tous les joueurs qui ont zéro DKP et aucun historique.",
    RAID = "Raid",
    RAIDCOMPLETEBONUSTT = "Prime donnée à tous ceux qui assistent à un raid jusqu'à la fin.",
    RAIDCOMPLETIONBONUS = "Prime d'achèvement de raid",
    RAIDDKPADJUSTBY = "DKP du raid ajusté par",
    RAIDENDED = "Raid Terminé",
    RAIDPAUSE = "Raid a été suspendu à",
    RAIDPAUSED = "Raid en pause",
    RAIDRESUME = "Le raid a été repris!",
    RAIDSTART = "Raid commencé!",
    RAIDTIMER = "Raid Timer",
    RAIDTIMERBONUSCONFIRM = "Êtes-vous sûr de vouloir appliquer la pri;e 'À l'heure' au raid ?",
    RAIDTIMERCONCLUDE = "La minuterie de raid a été conclue après",
    RANGE = "Portée",
    RANGEDPS = "DPS Distance",
    RANK = "Grade",
    RANKLIST = "Liste de grades",
    RANKLISTTTDESC = "Sélectionnez un grade et cliquez sur \"Ajouter des membres de guilde\" pour ajouter tous les membres de guilde du grade sélectionné à la table DKP.",
    REASON = "Motif",
    REASONFORADJUSTMENT = "Motif de l'ajustement",
    REASONTTDESC = "Sélectionnez le motif de l'ajustement de DKP. Si \"Prime de Boss éliminé\" ou \"Prime de Boss éliminé (Première fois)\" est sélectionné, un menu déroulant supplémentaire sera créé pour sélectionner la zone et le boss. \"Autre\" créera une zone de texte dans laquelle vous pourrez entrer un motif personnalisé.",
    REASONTTWARN = "Lorsqu'un boss est tué, la zone et le boss appropriés seront automatiquement sélectionnés pour vous.",
    REASSIGNED = "Réassigné",
    REASSIGNSELECTED = "Modifier l'entrée",
    RECENTHISTORYFOR = "Historique récente de",
    RECOMMENDRELOAD = "Les paramètres DKP ont été modifiés. Il est recommandé de recharger votre interface pour éviter toute erreur.",
    RELOADUICONFIRM = "Pour que ces paramètres prennent effet, nous devons recharger votre interface utilisateur. Voulez-vous faire cela maintenant ?",
    RELOADUIFORSETTINGS = "a mis à jour les définitions DKP. Souhaitez-vous recharger votre interface utilisateur pour refléter ces changements ?",
    REMOVE = "Supprimer",
    REMOVEENTRIES = "Supprimer les entrées",
    REMOVEENTRY = "Supprimer l'entrée",
    REMOVEFROMSTANDBY = "Retirer les joueurs sélectionnés du banc",
    REMOVESELECTEDENTRIES = "Supprimer les entrées sélectionnées",
    REMSELENTRIESTTDESC = "Supprime les joueurs sélectionnés de la table DKP. Toutes les références de ce joueur resteront (Historique DKP et Historique du butin) mais leur nom apparaîtra en gris.",
    REMSELENTRIESTTWARN = "Attention: Cette action est permanente.",
    REQUESTTABLESOFFICER = "Demander les tables DKP à jour à un officier.",
    RESETPREVCONFIRM = "Êtes-vous sûr de vouloir réinitialiser le DKP précédent?",
    RESETPREVDKP = "Réinitialiser l'évolution DKP",
    RESETPREVDKPTTDESC = "Réinitialise le compteur de l'évolution du DKP (petits chiffres gris +/- à côté du DKP actuel de chaque joueur). Cela n'a aucune incidence sur la fonctionnalité. Juste une référence de ce que chaque joueur a gagné / dépensé depuis sa dernière réinitialisation.",
    RESETPREVDKPTTWARN = "Recommandé de réinitialiser à intervalles réguliers (hebdomadaire, mensuel, etc.). Il s’agit d’une fonctionnalité QOL qui n’a aucune incidence sur les fonctionnalités.",
    RESETPREVIOUS = "Réinitialiser précédent",
    RESETSIN = "réinitialise dans",
    RESTORATION = "Restauration",
    RETRIBUTION = "Vindicte",
    RINGS = "Anneaux",
    ROLE = "Rôle",
    ROLL = "Jet",
    ROLLBIDDINGHEAD = "Enchère basée sur le jet",
    ROLLDECLINED = "Jet refusé. La plage de jet attendue est",
    ROLLDESCRIPTION = "Avec les enchères basées sur le jet, vous avez plusieurs options pour les paramètres. Vous pouvez sélectionner le type de jet que vous prévoyez d'utiliser ci-dessous. Les options que vous définissez ne seront pas des paramètres indiquant si un jet est accepté ou refusé, mais affichera plutôt les valeurs de jet attendues dans la fenêtre d'enchères pour examen. Vous pouvez cliquer avec le bouton droit de la souris sur leur rouleau et le supprimer s'il ne répond pas aux paramètres appropriés.",
    ROLLFOR = "Rouler pour",
    ROLLNOTACCEPTED = "Votre jet n'a pas été accepté. Vous avez seulement",
    ROLLRANGE = "Plage de jet",
    ROLLS = "Jets",
    ROLLSETTINGS = "Paramètres de jet",
    SAVESETTINGS = "Enregistrer les paramètres",
    SEARCH = "Recherche   ",
    SEARCHDESC = "Filtres de liste DKP. Recherches par nom, classe, spécification, rang et rôle.",
    SECONDBIDDER = "Seconde enchère la plus haute",
    SECONDBIDDERORMIN = "Seconde enchère ou valeur minimale", -- NEEDS TRANSLATION
    SECONDS = "Secondes",
    SELECTALL = "Tout sélectionner",
    SELECTALLVISIBLE = "Sélectionner les visibles",
    SELECTBOSS = "Sélectionner le Boss",
    SELECTED = "choisi",
    SELECTRANK = "Sélectionnez le grade",
    SELECTREASON = "Sélectionnez le motif",
    SELPLAYERSONLY = "Joueurs sélectionnés uniquement",
    SELPLAYERSTTDESC = "Applique le déclin DKP ci-dessus | cffff0000uniquement |r aux joueurs sélectionnés sur la table DKP",
    SELPLAYERSTTWARN = "Utile pour appliquer un déclin aux joueurs au-delà d'un seuil.",
    SENDWHITELIST = "Envoyer la liste blanche",
    SENDWHITELISTTTDESC = "Diffuse votre liste blanche à tous les officiers.",
    SENDWHITELISTTTWARN = "Je vous recommande de le faire lorsque tous les officiers sont en ligne. Si un agent ne reçoit pas cette liste blanche, il dispose de toutes les autorisations nécessaires. Ils ne pourront toutefois pas diffuser leurs informations à d'autres agents. Vous serez averti s'ils tentent de le faire. Si vous recevez cette notification, envoyez la liste blanche et leurs autorisations seront supprimées.",
    SETWHITELIST = "Définir la liste blanche",
    SETWHITELISTTTDESC1 = "Ajoute les officiers sélectionnés de la table DKP à la liste blanche. La liste blanche est utilisée pour | cffff0000limit | r les agents autorisés à modifier les valeurs DKP.",
    SETWHITELISTTTDESC2 = "L'utilisation de cette option sans sélection de joueurs effacera votre liste blanche.",
    SETWHITELISTTTWARN = "Seuls les officiers peuvent être inscrits sur la liste blanche. Cette option est utilisée exclusivement pour limiter les officiers ayant des droits d'officier dans cet addon. Si vous souhaitez que tous les agents aient la permission, laissez la liste blanche vide.",
    SHADOW = "Ombre",
    SHOULDERS = "Épaules",
    SLASHCOMMANDLIST = "Liste des commandes slash",
    SPEC = "Spec",
    STANDBYADJUSTBY = "DKP du banc ajusté par",
    STANDBYOPTIN = "Inscription au banc",
    STANDBYOPTINBEGIN = " a été tué. Merci d'écrire !standby (ou !standby nom_du_main si sur un alt, l'orthographe doit être précise.) sur le chat en guilde pour recevoir vos DKP. L'inscription expire dans 120 secondes.",
    STANDBYOPTINEND = "L'inscription au banc a expiré pour:",
    STANDBYOPTINTTDESC = "Annoncer à la guilde après la mort d’un boss demandant aux personnes en veille de s’inscrire en tapant !standby ou !standby NOM (si vous êtes sur un alt) dans le chat de guilde. L'inscription restera ouverte pendant deux minutes. La liste d'attente est effacée après chaque élimination de boss avant l'annonce de l'élimination.",
    STANDBYOPTINTTWARN = "Si la distribution DKP automatique sur élimination de boss est active, la distribution automatique pour le banc aura lieu à l'expiration du délai d'inscription de deux minutes.",
    STANDBYWHISPERRESP1 = "a été ajouté au banc.",
    STANDBYWHISPERRESP2 = "est déjà sur le banc.",
    STANDBYWHISPERRESP3 = "est invalide. Joueur non trouvé.",
    STANDBYWHISPERRESP4 = "Vous avez été ajouté au banc.",
    STANDBYWHISPERRESP5 = "Vous êtes déjà sur le banc.",
    STANDBYWHISPERRESP6 = "Joueur non trouvé.",
    STARTBIDDING = "Ouvrir l'enchère",
    STARTBIDDINGTTDESC = "Commence l'enchère. Les offres ne seront acceptées seulement durant l'enchère.",
    STARTBIDDINGTTWARN = "La durée des enchères peut être définie dans la zone \"Minuteur\". Commencer une deuxième session d'enchère pour un article n'effacera pas les enchères précédentes (à utiliser si quelqu'un claque une enchère à la dernière seconde).",
    STATIC = "Statique",
    STATICDESCRIPTION = [=[Avec les valeurs d’éléments statiques, une valeur statique est attribuée à tous les emplacements (ou objets individuels). Une enchère est soumise par chaque joueur (avec !bid) qui désire l'objet, et le joueur avec le plus de DKP gagne. Les options de valeur de prix sont "Entier" ou "Pourcent". 

    Ex: |cffa335ee|Hitem:19143::::::::120:577::::::|h[Flameguard Gauntlets]|h|r tombe et a une valeur statique de 50 DKP. Chaque joueur qui le souhaite utilise "!bid" via l’un des canaux ouverts (sélectionné ci-dessous). Le joueur avec le plus grand nombre de DKP disponibles gagne et se voit facturer cette valeur statique. Lisez les info-bulles pour plus d'informations.]=],
    STATICITEMVALUESHEAD = "Valeurs d'élément statiques",
    SUBMITBID = "Soumettre une offre",
    SUBMITBUGS = "de l'aide et soumettre des bugs",
    SUBZEROBIDDING = "Enchère insuffisante",
    SUBZEROBIDDINGTTDESC = [=[Permet aux joueurs d'enchérir s'ils ne disposent pas de suffisamment de DKP ou d'une enchère supérieure à leur DKP disponible (en fonction des paramètres de mode). 

    |cffff0000Valeurs minimales de l'enchère|r: Permet aux joueurs d'enchérir plus que leur nombre maximum, jusqu'à la Enchère maximum (définie ci-dessous), leur permettant d'entrer dans le négatif. 

    |cffff0000Autres|r: Permet au joueur de soumettre une enchère même si le prix de ses DKP disponibles est dépassé.]=],
    SUPPRESSBIDWHISP = "Supprimer les chuchotements d'enchère",
    SUPPRESSNOTIFICATIONS = "Supprimer les notifications d'addon",
    SUPPRESSNOTIFYTTDESC = "Masque tous les messages complémentaires affichés dans votre cadre de discussion.",
    SUPPRESSNOTIFYTTWARN = "Les mises à jour diffusées seront toujours reçues.",
    SuppressBIDWHISPTTDESC = "Supprime les chuchotements entrants et sortants liés aux enchères en cours.",
    SuppressBIDWHISPTTWARN = "Tous les autres chuchotements liés aux enchères ne seront toujours pas affichés.",
    SYNCALREADY = "Il y a déjà une synchronisation en cours.",
    SYNCCOMPLETE = "Synchronisation terminée",
    SYNCCOMPLETE2 = "Synchronisation terminée. Tous les joueurs sont à jour.",
    TABLEQUERYHEADER = "État de la table DKP de la guilde",
    TABLEQUERYNONOFFICER = "État de la table des non-officiers (en ligne)",
    TABLEQUERYOFFICER = "État de la table des officiers (en ligne)",
    TABLEQUERYOOD = "Périmé",
    TABLEQUERYSENT = "Interrogation de l'état de la table DKP de la guilde",
    TABLEQUERYUTD = "À jour",
    TABLESAREEMPTY = "Vos tables sont actuellement vides.",
    TABLEVIEWS = "Vues de la table",
    TAKINGBIDSON = "Prendre des offres sur",
    TANK = "Tank",
    NOTGUILDMASTER = "Disponible uniquement au Maitre de Guilde",  -- NEED TRANSLATION
    TEAM = "Table",
    TEAMS = "Tables",
    TEAMADD = "Ajouter une nouvelle table",
    TEAMADDDIALOG = "Êtes-vous sûrs de vouloir ajouter une nouvelle table. Cette opération est irréversible.",
    TEAMADDDESC = "Ajouter une nouvelle table à votre guilde (Disponible au MdG uniquement). Il n'existe pas encore de moyen de les supprimer.",
    TEAMRENAME = "Renommer une table.",
    TEAMRENAMESELECTED = "Renommer la table sélectionnée.",
    TEAMNAMEINPUTTOOLTIP = "Nom de la table",
    TEAMNAMEINPUTTOOLTIPDESC = "Pour changer le nom de la table sélectionnée",
    TEAMRENAMESELECTEDESC = "Permet au maître de guilde de renommer les tables via le menu déroulant.",
    TEAMCURRENTLIST = "Table sélectionnée",
    TEAMCURRENTLISTDESC = "Montre la liste de toutes les tables de la guilde.",
    TEAMCURRENTLISTDESC2 = "Toutes les tables enregistrent leurs données en se basant sur ce menu déroulant. Assurez vous de bien vérifier que la bonne table est sélectionnée avant de faire des modifications ou commencer un raid.",
    TEAMCURRENTLISTDESC3 = "Vous ne pouvez pas changer la table sélectionnée depuis ce menu. Pour la modifier, passer par '/dkp main window'",
    TEAMLIST = "Liste de tables",
    TEAMCURRENTLISTLABEL = "Sélecteur de table",
    TEAMLISTDESC = "Liste de toutes les tables de la guilde du joueur. Une guilde peut utiliser plusieurs tables en parallèle, ce qui sert pour les guildes avec plusieurs raids.",
    TEAMMANAGEMENTHEADER = "Section de gestion des tables de guilde",
    TEAMSELECT = "Sélectionner la table",
    TEAMCHANGERAIDINPROGRESS = "Vous ne pouvez pas changer de table pendant un raid !",
    NOTEAMCHOSEN = "Veuillez sélectionner une table dans le menu déroulant pour changer son nom", 
    TENSECONDSTOBID = "Plus que 10 secondes pour enchérir !",
    THISWILLREFUND = "Cela remboursera",
    TIMEELAPSED = "Temps écoulé",
    TIMEINTERVALBONUS = "Prime périodique",
    TIMERSIZE = "Taille de la minuterie",
    TIMERSIZETTDESC = "Échelle de minuterie de soumission / raid.",
    TIMERSIZETTWARN = "La position peut être ajustée en cliquant sur \"Déplacer le minuteur d'enchères\" et en le faisant glisser jusqu'à la position souhaitée.",
    TIMERWARNING = "Avertissement: Assurez-vous que vos paramètres de prime DKP soient correctement définis. Celles-ci peuvent être définies dans les zones \"Période\" et \"Prime\" ci-dessus, ainsi que dans toutes les \"Valeurs par défaut des primes DKP\" de l'onglet \"Options\" ci-dessous. Il est recommandé de définir ces valeurs et de les diffuser à tous les officiers via la fenêtre Modes DKP (accessible avec \"/dkp modes\" ou le bouton de l'onglet \"Options\" avant de les utiliser.",
    TO = "à",
    TOBID = "pour enchérir",
    TOBIDROLLRANGE = "Pour enchérir, utilisez /random. Votre plage attendue est visible sur la table DKP ou en utilisant",
    TOBIDUSE = "Pour enchérir, utiliser",
    TODKPLIST = "à la liste DKP ?",
    TOOMANYPLAYERSSELECT = "Trop de joueurs sélectionnés.",
    TORAID = "au raid",
    TOSEND = "envoyer",
    TOSTANDBYLIST = "au banc",
    TOTALDKP = "DKP totaux",
    TOTALDKPAWARD = "DKP totaux attribués",
    TOTALCommDKPUSERS = "Nombre total d'utilisateurs de CommDKP",
    TOWITHDRAWBID = "retirer votre enchère.",
    TRINKET = "Bijou",
    TTHISTORYCOUNT = "Compte d'historique d'infobulle",
    TTHISTORYCOUNTTTDESC = "Nombre d'entrées de l'historique du butin / dkp répertoriées dans l'info-bulle.",
    TWOHANDED = "À deux mains",
    TWOHANDEDWEAPONS = "Armes à deux mains",
    UNAUTHUPDATE1 = "a tenté de diffuser des tables modifiées. Il ne fait pas partie de vos officiers de la liste blanche.",
    UNAUTHUPDATE2 = "a tenté de diffuser des tables modifiées. Il n'est pas un officier désigné de votre guilde.",
    UNEXCUSEDABSENCE = "Absence injustifiée",
    UNEXCUSEDTTDESC = "Pénalité pour absence non excusée de raid.",
    UNEXCUSEDTTWARN = "Devrait être un nombre négatif.",
    UPDATING = "Mise à jour: ",
    UPTODATE = "à jour",
    USE = "Utilisation",
    USEPERCENTAGE = "Utiliser le pourcentage",
    USEPERCFORROLLS = "Utiliser le pourcentage pour les jets",
    USEPERCROLLSTTDESC = [=[Convertit les plages ci-dessus en% des joueurs DKP. IE: un joueur avec 1 000 dkp, avec ce qui précède réglé sur 70% - 100% devront utiliser 
    /random 700-1000]=],
    USEPERCROLLSTTWARN = "Si cette case est cochée, n'utilisez que des chiffres compris entre 0 et 100.",
    VALIDATEINPROG = "Il y a actuellement une validation en cours. Veuillez patienter...",
    VALIDATETABLES = "Valider les tables",
    VALIDATINGTABLES = "Validation et reconstruction de tables. Cela peut prendre quelques minutes ...",
    VALIDATIONCOMPLETE1 = "Validation terminée. Tous les profils sont précis!",
    VALIDATIONCOMPLETE2 = "Validation terminée. Les profils %s ont été reconstruits!",
    VALUE = "valeur",
    VERSION = "Version",
    VIEWALL = "Voir tout",
    VIEWCORERAID = "Voir les raideurs principaux",
    VIEWRAID = "Voir le raid",
    VIEWRAIDSTANDBY = "Voir le raid et le banc",
    VIEWS = "Les vues",
    VIEWSTANDBY = "Afficher le banc",
    VIEWWHITELISTBTN = "Voir la liste blanche",
    VIEWWHITELISTTTDESC = "Sélectionne tous les officiers de votre liste DKP figurant sur la liste blanche.",
    VISIBLE = "visible",
    WARNING = "ATTENTION",
    WEEKLYDECAY = "Déclin hebdomadaire",
    WEEKLYDECAYTTDESC = "Quantité de DKP par laquelle vous souhaitez réduire les entrées DKP sous forme de déclin hebdomadaire. Doit être un nombre positif. Si \"Joueurs sélectionnés uniquement\" n'est pas sélectionné ci-dessous, il s'appliquera à toutes les entrées.",
    WEEKLYDECAYTTWARN = "Attention: Ne peut pas être annulé.",
    WEEKLYDKPDECAY = "Déclin hebdomadaire du DKP",
    WHISPER = "Chuchotement",
    WHISPERCMDSHELP = "Whisper Command (Aux officiers désignés)",
    WHITELISTBROADCASTED = "Liste blanche diffusée",
    WHITELISTEMPTY = "Votre liste blanche est vide.",
    WHITELISTHEADER = [=[Paramètres de la liste blanche |CFF444444(Chef uniquement)(Alpha)|r

    Il est fortement recommandé de n'utiliser ce paramètre de liste blanche que si vous souhaitez limiter les autorisations requises par les officiers. Si vous souhaitez que tous les officiers disposent d'autorisations, ignorez entièrement cette fonctionnalité de paramètres. Utiliser avec précaution. (Si l'application de ces paramètres pose problème, ouvrez votre fichier \WTF\Accounts\ACCOUNT_NAME\SavedVariables\CommunityDKP.lua avec un éditeur de texte et supprimez la table CommDKP_Whitelist vers le bas.)]=],
    WIPETABLES = "Effacer les tables",
    WIPETABLESCONF = "Voulez-vous vraiment supprimer toutes les tables ? Vous pouvez récupérer toutes les informations d'un officier lorsque celui-ci est en ligne.",
    WIPETABLESTTDESC = "Efface toutes les données, y compris les tables DKP, l'historique du butin et l'historique DKP. Utilisez-le si des problèmes surviennent lors de la synchronisation pour recevoir des informations nouvelles et complètes d'un responsable disponible.",
    WITH = "avec",
    WON = "a gagné",
    WONBY = "gagné par",
    YES = "Oui",
    YOUCURRENTLYHAVE = "Vous avez actuellement",
    YOUHAVERECOVERED = "Vous avez récupéré un joueur. Veuillez recharger votre interface pour recalculer les valeurs.",
    YOUMUSTWAIT = "Vous devez attendre",
    YOURBID = "Votre enchère",
    YOURBIDOF = "Votre offre de",
    YOURTABLESARECURR = "Vos tables sont actuellement",
    ZEROSUMBALANCE = "Solde à somme nulle",
    ZEROSUMBALANCETTDESC = "Accumule automatiquement tout le DKP dépensé par les raiders pour être distribué une fois que le butin a été acheté.",
    ZEROSUMBANK = "Banque à somme nulle",
    ZEROSUMDESCRIPTION = [=[Avec le DKP à somme nulle, les articles peuvent avoir une valeur statique ou faire l'objet d'une enchère. Lorsqu'un joueur gagne un objet pour son enchère ou son coût, ce DKP en est déduit et réparti équitablement entre les membres du raid. Il est recommandé d’utiliser des décimales via l’option "DKP Arrondi" car des entiers arrondis pourraient provoquer une inflation ou une perte de DKP. Cela distribuerait 9 points au-dessus du coût. 

    Ex: |cffa335ee|Hitem:18824::::::::120:577::::::|h[Magma Tempered Boots]|h|r tombe et a un coût statique de 30 DKP. Le joueur A remporte l'offre en ayant le plus de DKP (ou distribué à la discrétion des chefs de raid en cas d'égalité) et leur DKP est réduit de 30. Ensuite, chaque membre du raid reçoit 0,75 DKP.]=],
    ZEROSUMHEAD = "Somme nulle",
    ZEROSUMITEMCOST = "Cout de l'objet (Somme nulle)",
    ZEROSUMITEMCOSTTTDESC = "Sélectionnez le type de coût d'article que vous souhaitez utiliser. La statique donne aux articles un coût défini. Alors que l'enchère minimum permet aux joueurs de soumettre une offre qui définit le coût pendant que vous définissez un seuil d'enchère minimum.",
    ZONE = "Zone",

    BROADCAST             = "Diffuser",
    BROADCASTWHICHDATA    = "Veuillez sélectionner les données que vous souhaitez diffuser.",
    REPAIRCOMP            = "Réparation terminée",
    REPAIRSTART           = "Réparer vos tables pour supprimer les entrées en double ou invalides.",
    MISSINGENT            = "Il manque une ou plusieurs entrées des officiers suivants",
    CREATED               = "Établi",
    BROADCASTTABLES       = "Tables de diffusion",
    BCASTINGTABLES        = "Tables de diffusion ...",
    FULLBROADCAST         = "Diffusion complète",
    MERGE2WEEKS           = "Fusionner les 2 dernières semaines",
    MERGE2WEEKSTTDESC     = "Diffuse les deux dernières semaines de données, en appliquant uniquement les entrées manquantes.",
    MERGE2WEEKSTTWARN     = "Utile pour fusionner des tables avec d'autres chefs de raid.",
    FULLBROADCASTTTDESC   = "Diffuse tous les tableaux aux sélections ci-dessus en remplaçant leurs données par des copies identiques de la vôtre.",
    FULLBROADCASTTTWARN   = "Si le destinataire a des données de raid que vous n'avez pas, elles seront perdues.",
    TOPLAYERTTDESC        = "Murmure sous la sélection aux joueurs individuels.",
    TOGUILDTTDESC         = "Diffuse en dessous de la sélection vers toute la guilde.",

    NEWERTABS1            = "Il semble que %s essaie de vous envoyer des tables peut-être obsolètes. Nouvelle entrée dans ces tableaux:",
    NEWERTABS2            = "Votre historique actuel contient de nouvelles entrées qui n'existent pas dans cette diffusion. L'acceptation écrasera vos données. Voulez-vous continuer?",
    OVERWRITETABLES       = "Une diffusion complète écrasera toutes les données des parties reçues avec des doubles exacts des vôtres. S'ils ont des données que vous n'avez pas, elles seront écrasées. Si vous souhaitez simplement envoyer des données manquantes, utilisez l'option \"Fusionner les 2 dernières semaines\". Souhaitez-vous continuer?",
    VALIDATEWARN          = "Cela recalculera tous les dkp des joueurs, la durée de vie gagnée et la durée de vie dépensée en fonction de leur historique complet. Assurez-vous de sauvegarder votre fichier de variables enregistré dans le cas où le résultat serait incorrect en raison d'entrées d'historique manquantes. Vous devez réinitialiser le dkp précédent (menu contextuel> sélectionner tout> réinitialiser le dkp précédent) pour tous les joueurs avant de courir afin que vous puissiez voir combien ils ont changé. Voulez-vous continuer?",
    PASS                  = "Passer",

    MIGRATIONDETECTED     = "CommunityDKP a détecté un addon MonolithDKP actif.|n|nVoulez vous migrer ses tables et paramètres vers CommunityDKP ?",
    MIGRATIONTEAM         = "CommunityDKP a détecté un addon MonolithDKP actif.|n|nVoulez vous migrer ses tables |nen tant que nouvelle table pour votre guilde |ndans CommunityDKP ?",
    MIGRATIONUNAVAILABLE  = "Veuillez désactiver MonolithDKP et recharger votre interface (/reload) pour utiliser CommunityDKP.",
    MIGRATIONCONFIRM      = "Cela va écraser vos tables et paramètres CommunityDKP.|n|nVoulez vous continuer ?", --TODO TRANSLATE:
    MIGRATIONCANCELED     = "Migration annulée.|n|nVeuillez désactiver MonolithDKP et recharger votre interface (/reload) pour continuer avec MonotlithDKP sans récupérer votre table et vos paramètres MonolithDKP.",
    MIGRATIONCOMPLETED    = "Migration réussie.|n|nVeuillez désactiver MonolithDKP et recharger votre interface (/reload).", --TODO TRANSLATE:

    --TODO TRANSLATE:
    CHANGELOG1 = "CommunityDKP - v3.2.4-r62",
    CHANGELOG2 = "fixed history display on mouseover",
    CHANGELOG3 = "",
    CHANGELOG4 = "",
    CHANGELOG5 = "",
    CHANGELOG6 = "",
    CHANGELOG7 = "Taidtuskecyh @ Gehennas",
    CHANGELOG8 = "CommunityDKP Discord: https://discord.gg/dXXK4vH",
    CHANGELOG9 = "",
    CHANGELOG10 = ""
          } 
end
